name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # 触发条件：main分支推送时

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug build context
        run: |
          echo "=== Frontend directory contents ==="
          ls -la ./frontend/
          echo "=== Current directory ==="
          pwd
          echo "=== Working directory contents ==="
          ls -la

      - name: Login to docker.cnb.coo
        uses: docker/login-action@v3
        with:
          registry: docker.cnb.cool
          username: cnb
          password: ${{ secrets.DOCKER_CNB_TOKEN }}  # 仓库密码/令牌(需在GitHub Secrets配置)

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: Dockerfile  # Dockerfile路径
          push: true
          tags: docker.cnb.cool/${{ vars.CNB_ORG }}/kube-gitops/frontend:v2.0.0  # 将CNB组织名替换为实际的组织名
          no-cache: true
          pull: true
